CREATE TABLE `dwd_vehicle_dm_key_dtc_llm_mapping` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `configuration_level` varchar(50) NOT NULL DEFAULT '' COMMENT '车辆配置',
  `ecu` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecu名称',
  `address` varchar(32) NOT NULL DEFAULT '' COMMENT 'ecu地址',
  `dtc_number` varchar(50) NOT NULL DEFAULT '' COMMENT 'dtc编码',
  `code_categories` varchar(50) NOT NULL DEFAULT '' COMMENT '分类',
  `dtc_description` text DEFAULT NULL COMMENT '英文描述',
  `dtc_description_ch` text DEFAULT NULL COMMENT '中文描述',
  `dtc_detail_description_ch` text DEFAULT NULL COMMENT '中文详细描述',
  `dtc_detail_description` text DEFAULT NULL COMMENT '英文详细描述',
  `dtc_root_cause` text DEFAULT NULL COMMENT 'DTC根本原因',
  `dtc_level` varchar(50) NOT NULL DEFAULT '' COMMENT 'DTC等级',
  `light_name` varchar(50) NOT NULL DEFAULT '' COMMENT '故障灯',
  `light_signal_name` varchar(50) NOT NULL DEFAULT '' COMMENT '故障灯报警信号名称',
  `light_signal_value` varchar(30) NOT NULL DEFAULT '' COMMENT '故障灯报警信号值',
  `classical_signal_name` varchar(50) NOT NULL DEFAULT '' COMMENT '文言报警信号名称',
  `classical_signal_value` varchar(30) NOT NULL DEFAULT '' COMMENT '文言报警信号值',
  `classical_content` varchar(100) NOT NULL DEFAULT '' COMMENT '文言报警显示内容',
  `national_level` varchar(50) NOT NULL DEFAULT '' COMMENT '32960等级',
  `enterprise_level` varchar(50) NOT NULL DEFAULT '' COMMENT '企标等级',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ecu_configuration_level` (`configuration_level`,`ecu`,`dtc_number`) USING BTREE,
  KEY `idx_address_configuration_level` (`configuration_level`,`address`,`dtc_number`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='重点故障DTC字典表';