CREATE TABLE `dwd_vehicle_dm_llm_key_dtc_dict` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '事件id',
  `configuration_level` varchar(50) NOT NULL DEFAULT '' COMMENT '车辆配置',
  `ecu` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecu名称',
  `address` varchar(32) DEFAULT NULL COMMENT 'ecu地址',
  `dtc_number` varchar(50) NOT NULL DEFAULT '' COMMENT 'dtc编码\r\n',
  `event_code` varchar(50) DEFAULT '' COMMENT '事件code',
  `code_categories` varchar(50) NOT NULL DEFAULT '' COMMENT '分类',
  `dtc_description` text COMMENT '英文描述',
  `dtc_description_ch` text COMMENT '中文描述',
  `dtc_detail_description_ch` text COMMENT '中文详细描述',
  `dtc_detail_description` text COMMENT '英文详细描述',
  `dtc_root_cause` varchar(500) DEFAULT '' COMMENT 'DTC根本原因',
  `dtc_level` varchar(50) NOT NULL DEFAULT '' COMMENT 'DTC等级',
  `failure_scenario` varchar(200) NOT NULL DEFAULT '' COMMENT '失效场景id',
  `signal` varchar(500) NOT NULL DEFAULT '' COMMENT '信号快照',
  `intelligent_analysis` text COMMENT '智能分析',
  `battery_model` varchar(500) NOT NULL DEFAULT '' COMMENT '整车电源模式',
  `vehicle_mode` varchar(100) NOT NULL DEFAULT '' COMMENT '车辆模式',
  `light_name` varchar(50) DEFAULT NULL COMMENT '故障灯',
  `light_signal_name` varchar(50) DEFAULT NULL COMMENT '故障灯报警信号名称',
  `light_signal_value` varchar(30) DEFAULT NULL COMMENT '故障灯报警信号值',
  `img_url` varchar(500) DEFAULT NULL COMMENT '图片地址',
  `light_id` varchar(20) DEFAULT NULL COMMENT '故障灯id',
  `img_name` varchar(100) DEFAULT NULL COMMENT '图片名称',
  `classical_signal_name` varchar(50) DEFAULT NULL COMMENT '文言报警信号名称',
  `classical_signal_value` varchar(30) DEFAULT NULL COMMENT '文言报警信号值',
  `classical_content` varchar(100) DEFAULT NULL COMMENT '文言报警显示内容',
  `national_level` varchar(50) NOT NULL DEFAULT '' COMMENT '32960等级',
  `enterprise_level` varchar(50) NOT NULL DEFAULT '' COMMENT '企标等级',
  `create_by` varchar(32) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) NOT NULL DEFAULT '' COMMENT '最近更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近更新时间',
  `del_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除字段',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ecu_configuration_level` (`configuration_level`,`ecu`,`dtc_number`) USING BTREE,
  KEY `idx_address_configuration_level` (`configuration_level`,`address`,`dtc_number`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='重点故障DTC字典表';